### ISSUE TITLE
MacOsx - CouchDb - CouchApp Problems

### ISSUE THREAD

**Issue by rasata** [jchris/couchapp#2]
Hi there,

I'm quite new to CouchDb, and I've discovered CouchApp recently. I've setup the version 0.9.1 of CouchDb on my Intel Mac.
It was working quqite well (view creation/Filtering, request etC....)
After all I setup CouchApp, but I got an odd error Message :(can anyone tell me if you have faced this problem ? 

{"error":"{bad_return_value,{os_process_error,\"OS process timed out.\"}}","reason":"{gen_server,call,\n            [<0.23365.2>,\n             {prompt,[<<\"list_tail\">>,\n                      {[{<<\"info\">>,\n                         {[{db_name,<<\"sofa\">>},\n                           {doc_count,1},\n                           {doc_del_count,0},\n                           {update_seq,14},\n                           {purge_seq,0},\n                           {compact_running,false},\n                           {disk_size,2006555},\n                           {instance_start_time,<<\"1250206253086256\">>}]}},\n                        {<<\"verb\">>,'GET'},\n                        {<<\"path\">>,\n                         [<<\"sofa\">>,<<\"_design\">>,<<\"sofa\">>,<<\"_list\">>,\n                          <<\"index\">>,<<\"recent-posts\">>]},\n                        {<<\"query\">>,\n                         {[{<<\"descending\">>,<<\"true\">>},\n                           {<<\"limit\">>,<<\"5\">>}]}},\n                        {<<\"headers\">>,\n                         {[{<<\"Accept\">>,\n                            <<\"text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8\">>},\n                           {<<\"Accept-Charset\">>,\n                            <<\"ISO-8859-1,utf-8;q=0.7,*;q=0.7\">>},\n                           {<<\"Accept-Encoding\">>,<<\"gzip,deflate\">>},\n                           {<<\"Accept-Language\">>,\n                            <<\"fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3\">>},\n                           {<<\"Connection\">>,<<\"keep-alive\">>},\n                           {<<\"Host\">>,<<\"localhost:5984\">>},\n                           {<<\"Keep-Alive\">>,<<\"300\">>},\n                           {<<\"User-Agent\">>,\n                            <<\"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; fr; rv:1.9.0.11) Gecko/2009060214 Firefox/3.0.11\">>}]}},\n                        {<<\"body\">>,undefined},\n                        {<<\"form\">>,{[]}},\n                        {<<\"cookie\">>,{[]}}]}]},\n             infinity]}"}

**Comment by jchris** [comment]
thanks for reporting..

this looks like something in your function is returning a crasher.... maybe the "undefined" in your body there, which probably means a problem with your function.

you might try couchdb trunk (or wait for 0.10 which is soon) the error messages are improved since 0.9.1.

a good place to get help is the  #couchdb or #couchapp channels on irc.freenode.net
